media: assets

content:
  - name: posts
    label: 文章
    type: collection
    path: '_posts'
    view:
      fields: [ title, published, date, category, tags, lng_pair ]
    fields:
      - name: title
        label: 文章标题
        type: string
        required: true

      - name: meta_description
        label: 页面描述
        type: string
        required: false

      - name: img
        label: 缩略图
        type: image
        required: false

      - name: date
        label: 发布日期
        type: date
        required: true

      - name: meta_modify_date
        label: 修改日期
        type: date
        required: false

      - name: category
        label: 分类
        type: select
        options:
          values:
          - value: catinfo
            label: 猫档案
          - value: activity
            label: 活动
        required: true

      - name: tags
        label: 标签
        type: select
        options:
          values:
          - value: yanchang
            label: 延长校区
          - value: baoshan
            label: 宝山校区
          - value: jiading
            label: 嘉定校区
        required: true

      - name: comments_disable
        label: 禁用评论
        type: boolean
        required: false
        default: false

      # 功能配置
      - name: image_viewer_on
        label: 启用图片查看器
        type: boolean
        required: false
        default: false

      - name: image_lazy_loader_on
        label: 启用图片懒加载
        type: boolean
        required: false
        default: true

      - name: on_site_search_exclude
        label: 排除站内搜索
        type: boolean
        required: false
        default: false

      - name: search_engine_exclude
        label: 排除搜索引擎
        type: boolean
        required: false
        default: false

      - name: published
        label: 发布状态
        type: boolean
        required: false
        default: true

      - name: lng_pair
        label: 多语言页面配对ID
        type: string
        required: true
        
      - name: body
        label: 文章内容
        type: rich-text
        required: true

  # ... config 部分保持不变 ...