media: assets

content:
  - name: posts
    label: 文章
    type: collection
    path: '_posts'
    view:
      fields: [ title, published, date, category, tags, lng_pair ]
    fields:
      - name: title
        label: 文章标题
        type: string
        required: true

      - name: meta_description
        label: 页面描述
        type: string
        required: false

      - name: img
        label: 缩略图
        type: image
        required: false

      - name: date
        label: 发布日期
        type: date
        required: true
        options:
         format: "yyyy-MM-dd HH:mm:ss xx"

      - name: meta_modify_date
        label: 修改日期
        type: date
        required: false
        options:
         format: "yyyy-MM-dd HH:mm:ss xx"


      - name: category
        label: 分类
        type: select
        options:
          values: [ 猫档案, 活动 ]
        required: true

      - name: tags
        label: 校区
        type: select
        options:
          values: [ 延长校区, 宝山校区, 嘉定校区 ]
        required: true

      - name: comments_disable
        label: 禁用评论
        type: boolean
        required: false
        default: false

      # 功能配置
      - name: image_viewer_on
        label: 启用图片查看器
        type: boolean
        required: false
        default: false

      - name: image_lazy_loader_on
        label: 启用图片懒加载
        type: boolean
        required: false
        default: true

      - name: on_site_search_exclude
        label: 排除站内搜索
        type: boolean
        required: false
        default: false

      - name: search_engine_exclude
        label: 排除搜索引擎
        type: boolean
        required: false
        default: false

      - name: published
        label: 发布状态
        type: boolean
        required: false
        default: true

      - name: lng_pair
        label: 多语言页面配对ID
        type: string
        required: true
        
      - name: body
        label: 文章内容
        type: rich-text
        required: true

  - name: config
    label: Jekyll 配置
    type: file
    path: _config.yml
    fields:
    - name: title
      label: 网站标题
      type: string
      required: true
  
    - name: description
      label: 网站描述
      type: string
      required: false
  
    - name: url
      label: 网站URL
      type: string
      pattern: '^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$'
      required: true
  
    - name: cover
      label: 预览图片
      type: image