name: Create release notes

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    if: ${{ github.repository == 'MrGreensWorkshop/MrGreen-JekyllTheme' && startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create release from issues linked to PRs
        uses: ./.github/actions/create-release-notes
